config/routes.rb
Rails.application.routes.draw do
  resources :products, controller: :stocks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(:id)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>製品管理</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>製品一覧</h1>

<table>
    <tr>
        <th>名称</th>
    </tr>
    <% @products.each do |p|%>
    <tr>
        <td><%= p.name %></td>
        <!-- <td><%= link_to '詳細', action: :show, id: p.id %></td> -->
        <!-- <td><%= link_to '詳細', product_path(p) %></td> -->
        <td><%= link_to '詳細', p %></td>
    </tr>
    <% end %>
</table>

app/views/products/show.html.erb
<h1>製品の詳細情報</h1>

<table>
    <tr>
        <th>名称</th>
        <td><%= @product.name %></td>
    </tr>
    <tr>
        <th>価格</th>
        <td>&yen;<%= number_with_delimiter(@product.price) %></td>
    </tr>
</table>
<p><%= link_to '製品一覧', products_path %></p>